---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: can
  description: SDK for working with CAN
spec:
  type: library
  lifecycle: production
  owner: team-ads-platform
  system: can
